#--Server configuration
server:
  port: 8080

#-- MySql Server Configuration
spring:
  datasource:
    url: jdbc:mysql://furdb.cpptvtdioztc.ap-southeast-1.rds.amazonaws.com/FURNITURESHOP
    username: admin
    password: x9NK9AAvFTrlcRemdO4d
    driver-class-name: com.mysql.cj.jdbc.Driver

#-- MyBatis Configuration
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.scscyber.fur.model
  configuration:
    map-underscore-to-camel-case: true

#-- Email
email.user-name: chinghia28.1997@gmail.com
email.password: qaznghia123